services:
  api:
    build: 
      context: .
      dockerfile: app/Dockerfile
    container_name: PScanner
    restart: unless-stopped
    volumes:
      - ./backups:/backups
  nginx:
    image: nginx:alpine
    container_name: PScanner-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/src/templates:/usr/share/nginx/html:ro
    depends_on:
      - api
